plugins {
    id 'com.github.johnrengelman.shadow'
}

loom {
    accessWidenerPath = file("src/main/resources/super_resolution.accesswidener")
}


architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
    modImplementation "dev.architectury:architectury-fabric:$rootProject.architectury_api_version"
    modImplementation fileTree(dir: 'libs', include: ['*.jar'])
    modImplementation("maven.modrinth:timeless-and-classics-zero:1.0.2-hotfix3-fabric,1.20.1")
    modImplementation("maven.modrinth:forge-config-api-port:v8.0.1-1.20.1-Fabric-fabric,1.20.1")
    modImplementation("maven.modrinth:spark:1.10.53-fabric-fabric,1.20.1")
    modImplementation("maven.modrinth:reeses-sodium-options:mc1.20.1-1.7.2-fabric,1.20.1")
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
    implementation "io.github.spair:imgui-java-app:1.87.5"
    implementation "io.github.spair:imgui-java-binding:1.87.5"
    implementation "io.github.spair:imgui-java-lwjgl3:1.87.5"
    implementation "org.anarres:jcpp:1.4.14"
    implementation "org.antlr:antlr4-runtime:4.13.1"
    implementation "io.github.douira:glsl-transformer:2.0.1"
    implementation("org.lwjgl:lwjgl-vulkan:$lwjglVersion")
    include("org.lwjgl:lwjgl-vulkan:$lwjglVersion")

}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
}
loom {
    accessWidenerPath = file('src/main/resources/super_resolution.accesswidener')
}